<?php

use Drupal\Core\Form\FormStateInterface;

function company_dropdown_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'views_exposed_form' && isset($form['field_company'])) {

    $connection = \Drupal::database();

    $ids = $connection->select('profile__field_company', 'fc')
      ->fields('fc', ['field_company_target_id'])
      ->distinct()
      ->condition('field_company_target_id', 0, '>')
      ->execute()
      ->fetchCol();

    if ($ids) {

      $profiles = \Drupal::entityTypeManager()
        ->getStorage('profile')
        ->loadMultiple($ids);

      $options = [];

      foreach ($profiles as $profile) {
        $options[$profile->id()] = $profile->label();
      }

      asort($options);

      $form['field_company']['#type'] = 'select';
      $form['field_company']['#options'] = ['' => '- Select -'] + $options;
      $form['field_company']['#multiple'] = FALSE;

    }

  }

}
